apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30565 # On utilise ce port spécifique
  selector:
    app: minecraft